---
title: "Progetto di Health"
output: html_document
date: '2023-04-11'
---

```{r}
install.packages("rlang")
```
#visualizzo df

```{r}
show(GermanH)
```


#Importo il dataset e procedo con un bel summary


```{r cars}
summary(GermanH)
```
#Trasformo tutti i valori nulli in 0

```{r}
GermanH[is.na(GermanH)] <- 0
```

#Osservo quanti valori pari a 0 (ovvero nulli) presentano le singole colonne

```{r}
colSums(GermanH == 0)
```
#Check del numero di righe differenti e spero siano 7748


```{r}
GermanH_ok <- GermanH[apply(GermanH!=0,1,all),]
```

```{r}
colSums(GermanH_ok ==0)
```


```{r}
nrow(GermanH_ok[duplicated(GermanH$idnum)])
```


```{r echo=T, results=FALSE, message=FALSE}
write.csv(GermanH_ok, "C:\\Users\\eugen\\Desktop\\Eugenio\\German_final.csv", row.names= FALSE)
```


```{r echo=T, results=FALSE, message=FALSE}
install.packages("ggplot", dependencies = TRUE)
```
```{r}

```


```{r echo=T, results=FALSE, message=FALSE}
install.packages("ggplot", dependencies=TRUE)
```


```{r echo=T, results=FALSE, message=FALSE}
install.packages("ggpubr", dependencies=TRUE)
```



```{r}
library(ggplot2)
library(ggpubr)
```

#Faccio un pò di plot come un bastardo

```{r}
ggplot(GermanH_ok, aes(smoke)) +
  geom_bar(fill = "#0073C2FF") 
ggplot(GermanH_ok, aes(sex)) +
  geom_bar(fill = "#0073C2FF") 
ggplot(GermanH_ok, aes(married)) +
  geom_bar(fill = "#0073C2FF") 
ggplot(GermanH_ok, aes(kids)) +
  geom_bar(fill = "#0073C2FF") 
ggplot(GermanH_ok, aes(work)) +
  geom_bar(fill = "#0073C2FF") 
ggplot(GermanH_ok, aes(education)) +
  geom_bar(fill = "#0073C2FF") 
 
```
```{r}
ggplot(GermanH_ok, aes(age)) +
  geom_bar(fill = "#0073C2FF")
```

